FROM python:3.12

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFRED=1

RUN apt-get update \
    && install -y --no-install-recomends \
        build-essential \
        libpg-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN apt-get --upgade pip && \
    pip install --no-cache-dir -r requirements.txt

COPY . .