# Generated by Django 4.2.17 on 2026-07-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, verbose_name='Банер')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banner/image/%Y/%m/', verbose_name='Фото_банер')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
            ],
        ),
    ]
