# Generated by Django 6.0.7 on 2026-07-20 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Назва')),
                ('address', models.CharField(max_length=255, verbose_name='Адреса')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Видалити')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склади',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='StockReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Кількість')),
                ('supplier', models.CharField(blank=True, max_length=255, verbose_name='Постачальник')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата надходження')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_receipts', to='main.product', verbose_name='Товар')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='warehouse.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Надходження товару',
                'verbose_name_plural': 'Надходження товарів',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='StockIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Кількість')),
                ('reason', models.CharField(choices=[('sale', 'Продаж'), ('write_off', 'Списання'), ('return', 'Повернення')], max_length=20, verbose_name='Причина')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_issues', to='main.product', verbose_name='Товар')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='warehouse.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Вибуття товару',
                'verbose_name_plural': 'Вибуття товарів',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Кількість')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='main.product', verbose_name='Товар')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='warehouse.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Залишок',
                'verbose_name_plural': 'Залишки',
                'unique_together': {('warehouse', 'product')},
            },
        ),
    ]
