# Generated by Django 6.0.7 on 2026-07-20 14:31

import apps.users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, validators=[apps.users.validators.validator_phone], verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
