# Generated by Django 4.2.17 on 2026-07-14 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Заголовок баннера')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banner/images/%Y/%m/', verbose_name='Фото баннера')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка')),
                ('banner_type', models.CharField(choices=[('sale', 'Знижка'), ('promo', 'Акції'), ('new', 'Новинки')], default='promo', max_length=40, verbose_name='Тип баннера')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='main.product')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннери',
                'ordering': ['-created_at'],
            },
        ),
    ]
