# Generated by Django 6.0.7 on 2026-07-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='Артикул'),
        ),
    ]
