# Generated by Django 4.2.17 on 2026-07-12 19:57

import apps.main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_is_popular_product_sold_count_product_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=50, unique=True, validators=[apps.main.validators.validator_category_title], verbose_name='Каталог'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[apps.main.validators.validator_discount], verbose_name='Скидка%'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='main_image_products/products/%Y/%m/', verbose_name='Фото продукту'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[apps.main.validators.validator_price], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images_gallery/images/%Y/%m', verbose_name='Фото товарів'),
        ),
    ]
